"""initial durable notification state"""

import sqlalchemy as sa
from alembic import op

revision = "f2b55311b3a2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=80), nullable=False),
        sa.Column("auth", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_key", sa.String(length=500), nullable=False),
        sa.Column("resource_key", sa.String(length=400), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disposition", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unique_key"),
    )
    op.create_index(op.f("ix_events_resource_key"), "events", ["resource_key"], unique=False)
    op.create_table(
        "health",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "leases",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("owner", sa.String(length=80), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "notification_rules",
        sa.Column("scope", sa.String(length=400), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("scope"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_key", sa.String(length=600), nullable=False),
        sa.Column("resource_key", sa.String(length=400), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=80), nullable=True),
        sa.Column("message_id", sa.String(length=180), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unique_key"),
    )
    op.create_index(op.f("ix_outbox_available_at"), "outbox", ["available_at"], unique=False)
    op.create_index(op.f("ix_outbox_resource_key"), "outbox", ["resource_key"], unique=False)
    op.create_index(op.f("ix_outbox_status"), "outbox", ["status"], unique=False)
    op.create_table(
        "reminder_jobs",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("resource_key", sa.String(length=400), nullable=False),
        sa.Column("boundary_type", sa.String(length=20), nullable=False),
        sa.Column("boundary_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("offset_seconds", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("rule_fingerprint", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_reminder_jobs_resource_key"), "reminder_jobs", ["resource_key"], unique=False)
    op.create_index(op.f("ix_reminder_jobs_scheduled_at"), "reminder_jobs", ["scheduled_at"], unique=False)
    op.create_index(op.f("ix_reminder_jobs_status"), "reminder_jobs", ["status"], unique=False)
    op.create_table(
        "resources",
        sa.Column("key", sa.String(length=400), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("external_id", sa.String(length=160), nullable=False),
        sa.Column("course_id", sa.String(length=80), nullable=False),
        sa.Column("scope", sa.String(length=400), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("missing_count", sa.Integer(), nullable=False),
        sa.Column("availability", sa.String(length=40), nullable=False),
        sa.Column("local", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_resources_course_id"), "resources", ["course_id"], unique=False)
    op.create_index(op.f("ix_resources_kind"), "resources", ["kind"], unique=False)
    op.create_index(op.f("ix_resources_scope"), "resources", ["scope"], unique=False)
    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sync_scopes",
        sa.Column("key", sa.String(length=400), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("course_id", sa.String(length=80), nullable=False),
        sa.Column("baseline", sa.Boolean(), nullable=False),
        sa.Column("pages", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column("last_attempt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_scopes")
    op.drop_table("sync_runs")
    op.drop_index(op.f("ix_resources_scope"), table_name="resources")
    op.drop_index(op.f("ix_resources_kind"), table_name="resources")
    op.drop_index(op.f("ix_resources_course_id"), table_name="resources")
    op.drop_table("resources")
    op.drop_index(op.f("ix_reminder_jobs_status"), table_name="reminder_jobs")
    op.drop_index(op.f("ix_reminder_jobs_scheduled_at"), table_name="reminder_jobs")
    op.drop_index(op.f("ix_reminder_jobs_resource_key"), table_name="reminder_jobs")
    op.drop_table("reminder_jobs")
    op.drop_index(op.f("ix_outbox_status"), table_name="outbox")
    op.drop_index(op.f("ix_outbox_resource_key"), table_name="outbox")
    op.drop_index(op.f("ix_outbox_available_at"), table_name="outbox")
    op.drop_table("outbox")
    op.drop_table("notification_rules")
    op.drop_table("leases")
    op.drop_table("health")
    op.drop_index(op.f("ix_events_resource_key"), table_name="events")
    op.drop_table("events")
    op.drop_table("accounts")
    # ### end Alembic commands ###
